# Generated by Django 5.0.3 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Телефон')),
                ('education', models.CharField(max_length=300, verbose_name='Образование')),
                ('photo', models.ImageField(upload_to='person/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
