# Generated by Django 5.0.3 on 2024-03-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_comments_person_alter_comments_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='specialization',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_person', to='person.person', verbose_name='Продукт'),
        ),
    ]
