# Generated by Django 5.0.3 on 2024-03-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_specialization_alter_comments_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название специализации')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.specialization'),
        ),
    ]
