# Generated by Django 5.0.3 on 2024-03-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_specialization_alter_person_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialization/'),
        ),
    ]
