# Generated by Django 5.0.3 on 2024-03-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_specialization_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialization/', verbose_name='Фото'),
        ),
    ]
